//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1760081.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuHoatDong
    {
        public string UserName { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string HanhDong { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
