//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1760081.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiLienQuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiLienQuan()
        {
            this.LichSuTinhTrangNhiems = new HashSet<LichSuTinhTrangNhiem>();
            this.NguoiLienQuan1 = new HashSet<NguoiLienQuan>();
        }
    
        public string HoTen { get; set; }
        public string Cmnd { get; set; }
        public Nullable<short> NamSinh { get; set; }
        public string SoNhaDuong { get; set; }
        public Nullable<int> PhuongXa { get; set; }
        public string NguoiLay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuTinhTrangNhiem> LichSuTinhTrangNhiems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiLienQuan> NguoiLienQuan1 { get; set; }
        public virtual NguoiLienQuan NguoiLienQuan2 { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
