//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1760081.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoiDieuTriCachLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NoiDieuTriCachLy()
        {
            this.LichSuTinhTrangNhiems = new HashSet<LichSuTinhTrangNhiem>();
        }
    
        public int id { get; set; }
        public string Ten { get; set; }
        public int SucChua { get; set; }
        public Nullable<int> SoLuongHienTaiTiepNhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuTinhTrangNhiem> LichSuTinhTrangNhiems { get; set; }
    }
}
